stadala23/Marks-Mgmt-system

App.java

Introducing Classes and Proper Implementation

Introducing Classes and Proper Implementation

---

App.java

Added Inheritance and Proper Implementation

Added Inheritance and Proper Implementation

---

App.java

Reverts stadala23/Marks-Mgmt-system#5

Revert "Added Inheritance and Proper Implementation"

---

App.java

Recorrecting Inheritance Code due to Git Merge Issue Corrections and Proper Implementation

Recorrecting Inheritance Code due to Git Merge Issue Corrections and Proper Implementation

---

src/marksmgmtcode/UndergraduateStudent.java

Created New Java File UndergraduateStudent.java for Code Readability

Created New Java File UndergraduateStudent.java for Code Readability

---

src/marksmgmtcode/App.java

Added Exception Handling Logic in App.Java

Added Exception Handling Logic in App.Java

---

src/marksmgmtcode/StudentManager.java

Added Exception Handling Logic in deleteStudent Method of StudentManager.Java

Added Exception Handling Logic in deleteStudent Method of StudentManager

---

src/marksmgmtcode/StudentManager.java

Added Exception Handling Logic in getBestStudentInProgrammingFundamentals Method of StudentManager.java

Added Exception Handling Logic in getBestStudentInProgrammingFundamentals Method of StudentManager

---

src/marksmgmtcode/Menu.java

Added Exception Handling Logic in addUndergraduateStudent Method of Menu.Java

Added Exception Handling Logic in addUndergraduateStudent Method of Menu

---

src/marksmgmtcode/Menu.java

Added Exception Handling Logic in addGraduateStudent Method of Menu.Java

Added Exception Handling Logic in addGraduateStudent Method of Menu

---

src/marksmgmtcode/Menu.java

Added Exception Handling Logic in updatestudentname Method of Menu.Java

Added Exception Handling Logic in updatestudentname Method of Menu.Java

---

src/marksmgmtcode/Menu.java

Added Exception Handling Logic in updateStudentMarks Method of Menu.Java

Added Exception Handling Logic in updateStudentMarks Method of Menu.Java

---

src/marksmgmtcode/Menu.java

Added Exception Handling Logic in displayStudents Method of Menu.Java

Added Exception Handling Logic in displayStudents Method of Menu.Java

---

src/marksmgmtcode/Student.java

Changed Student variable References for id and name along with its Code Refactoring

Changed Student variable References for id and name along with its Code Refactoring

---

src/marksmgmtcode/Student.java

Changed Student variable References for DBMS Marks and other references along with its Code Refactoring

Changed Student variable References for DBMS Marks and other references along with its Code Refactoring

---

src/marksmgmtcode/UndergraduateStudent.java

Changed undergraduate student variable References for major along with its Code Refactoring

Changed undergraduate student variable References for major along with its Code Refactoring

---

src/marksmgmtcode/GraduateStudent.java
src/marksmgmtcode/StudentManager.java

Changed graduate student variable References for major along with its Code Refactoring

Changed graduate student variable References for major along with its Code Refactoring

---

src/marksmgmtcode/Menu.java

Changed Menu.java variable References for display menu method along with its Code Refactoring

Changed Menu.java variable References for display menu method along with its Code Refactoring

---

src/marksmgmtcode/Menu.java

Changed Menu.java variable References for adding undergraduate references along with its Code Refactoring

Changed Menu.java variable References for adding undergraduate references along with its Code Refactoring

---

src/marksmgmtcode/Menu.java

Changed Menu.java variable References for add grad student and update student name references along with its Code Refactoring

Changed Menu.java variable References for add grad student and update student name references along with its Code Refactoring

---

src/marksmgmtcode/Menu.java

Changed Menu.java variable References for updating student marks, deleting students, and displaying students, along with their code refactoring

Changed Menu.java variable References for updating student marks, deleting students, and displaying students, along with their code refactoring

---

src/marksmgmtcode/Menu.java

Changed Menu.java variable References in remaining methods along with its Code Refactoring

Changed Menu.java variable References in remaining methods along with its Code Refactoring

---

src/marksmgmtcode/App.java

Added comments for App.java

---

src/marksmgmtcode/GraduateStudent.java

Added comments for Graduatestudent.java

Added comments for Graduatestudent.java

---

src/marksmgmtcode/Menu.java

Added comments for Menu.java

---

src/marksmgmtcode/Student.java

Added comments for student.Java

Added comments for student.Java

---

src/marksmgmtcode/UndergraduateStudent.java

Added comments for UndergraduateStudent.Java

Development mahesh comments

---

README.md

Update README.md to clearly describe about the application

Update README.md to clearly describe about the application
